
#include "../common/cvedix_node.h"

namespace cvedix_nodes {
    // sync mode
    enum class cvedix_sync_mode {
        // merge target (cvedix_frame_target/cvedix_frame_face_target/...) collections between the 1st cvedix_frame_meta and the 2nd cvedix_frame_meta
        // mainly used for sync primary infer data which created by those derived from cvedix_primary_infer_node
        MERGE = 0,
        // update properties of target(cvedix_frame_target/cvedix_frame_face_target/...) from the 1st cvedix_frame_meta to 2nd cvedix_frame_meta
        // mainly used for sync secondary infer data which generated by those derived from cvedix_secondary_infer_node， could also be used for sync other properties like tracking ids.
        UPDATE = 1
    };

    // sync data(hold by cvedix_frame_meta) for the same frame in the same channel
    // mainly be used to sync infer results between parallel nodes which have been splited by cvedix_split_node before in the same channel
    // note: it could also sync cvedix_control_meta, just filter the same control meta by control uid.
    class cvedix_sync_node: public cvedix_node
    {
    private:
        // do sync work
        void sync(std::shared_ptr<cvedix_objects::cvedix_frame_meta> des, std::shared_ptr<cvedix_objects::cvedix_frame_meta> src);
        // sync mode
        cvedix_sync_mode mode = cvedix_sync_mode::MERGE;
        // push to downstream directly after waiting a period of time(milliseconds), because we can not wait infinitely
        int timeout = 40;  // wait for 40ms for each frame since 25fps is normal for video stream

        /* multi-channel supported*/
        std::map<int, int> all_indexs_last_syned;
        std::map<int, std::string> all_control_uids_last_synced;
        std::map<int, std::vector<std::shared_ptr<cvedix_objects::cvedix_meta>>> all_meta_waiting_for_sync;
    protected:
        // re-implementation
        virtual std::shared_ptr<cvedix_objects::cvedix_meta> handle_frame_meta(std::shared_ptr<cvedix_objects::cvedix_frame_meta> meta) override;
        // re-implementation
        virtual std::shared_ptr<cvedix_objects::cvedix_meta> handle_control_meta(std::shared_ptr<cvedix_objects::cvedix_control_meta> meta) override;
    public:
        cvedix_sync_node(std::string node_name, cvedix_sync_mode mode = cvedix_sync_mode::MERGE, int timeout = 40);
        ~cvedix_sync_node();
    };
}