#pragma once

#include "cvedix_control_meta.h"

namespace cvedix_objects {
    // control meta for image recording, it is a specific type of cvedix_control_meta.
    // when cvedix_record_node handle this control meta, the node will save the Latest Next frame in pipeline to disk.
    // refer to ./nodes/record/README.md for more details
    class cvedix_image_record_control_meta: public cvedix_control_meta
    {
    private:
        /* data */
    public:
        cvedix_image_record_control_meta(int channel_index, 
                                    std::string image_file_name_without_ext,
                                    bool osd = false);
        ~cvedix_image_record_control_meta();

        // copy myself
        virtual std::shared_ptr<cvedix_meta> clone() override;

        // file name without extension, like 2022-10-20_22-30-20_aaa_bbb, which should be a meaningful and unique name.
        // generated by sender who want to record image
        std::string image_file_name_without_ext;

        // record type (osd frame or not)
        bool osd = false;
    };

}